import { DraftBanner } from "@/components/DraftBanner"
import { UserProvider } from "@/context/UserContext"
import { getAuthUser } from "@/lib/auth"
import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import { draftMode } from "next/headers"
import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const user = await getAuthUser()
  const { isEnabled } = await draftMode()

  return (
    <html lang="ja">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {isEnabled && <DraftBanner />}
        <UserProvider initialUser={user}>{children}</UserProvider>
      </body>
    </html>
  )
}
